# Generated by Django 5.2.8 on 2025-12-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pDesc', models.TextField()),
                ('pPrice', models.IntegerField()),
                ('pCat', models.CharField(max_length=100)),
                ('pImg', models.CharField(max_length=100)),
            ],
        ),
    ]
