# Generated by Django 5.2.8 on 2025-12-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trainers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
